### ISSUE TITLE
flirController.readNextFrame() always returns false?

### ISSUE THREAD

**Issue by ojohnson2** [NachtRaveVL/Lepton-FLiR-Arduino#4]
I'm using an arduino Uno and am attempting to utilize this code however I cannot get flirController.readNextFrame() to return true so I can actually utilize the camera. I recognize that I am inexperienced with arduino but I believe I have everything wired correctly as it is plugged directly into the board with the pins matching the corresponding functions. 

edit: I am just starting off with the simple example so I wouldn't be throwing too much at it at once

**Comment by NachtRaveVL** [comment]
Unfortunately a UNO will not be powerful enough to correctly grab the frame in time before the sensor invalidates the feed.

I couldn’t even get this to work fast enough with a Duo, and would suspect you’d need at least a Teensy 3.4 or better to even get this library working in any way. *le sigh*

**Comment by ojohnson2** [comment]
I appreciate the information, as unfortunate as it may be. But hey, saved me some time and a headache.

________________________________

**Comment by GoncaloRodrigues241** [comment]
Hello!

I have the same problem, flirController.readNextframe() is always returning false and I am using an Adafruit ESP32 Feather.

How can I solve it?

Tkank you
