### ISSUE TITLE
Calculating RAD Spotmeter using default RAD ROI

### ISSUE THREAD

**Issue by acgvar** [NachtRaveVL/Lepton-FLiR-Arduino#5]
Hi! Does your code support the calculation of RAD Spotmeter for the default ROI? Will it work with the Arduino Uno?

**Comment by NachtRaveVL** [comment]
UNO is far too unpowered. I wasn't able to get this working on a Duo. Likely you would need a Teensy 3.5/3.6, but even then it may take modifications to the library itself.

Also, I am uncertain what RAD/ROI refer to, but most likely not. Although I welcome you to look at the code closer. :)
