### ISSUE TITLE
"Lepton FLiR" does not name a type

### ISSUE THREAD

**Issue by pablopar2** [NachtRaveVL/Lepton-FLiR-Arduino#6]
That error shows up in this line:
LeptonFLiR flirController(); // 

I don't know how to fix it. 
I uploaded the libraries LeptonFLiR.h, the LeptonFLiR.cpp, and the LeptonFLiRDefs.h
I don't know if something is missing, let me know please and thank you.

**Comment by NachtRaveVL** [comment]
Hey pablo, thanks for commenting, and my apologies for the delay, but I had considered this repository rather broken/state-of-disrepair for quite some time, but most recently picked it back up given the 600 Mhz Teensy 4.0 line. We are in a transitional period with the library in terms of its future direction, so apologies for the mess.

You may want to be sure that you placed the library files in your Documents/Arduino/libraries/Lepton-FLiR-Arduino folder. You should only, if ever, need to upload the main sketch you're working on.

There also has been some changes that wound up breaking the Arduino build system. I'm currently working in my off-hours to develop some fixes.
